config/routes.rb
Rails.application.routes.draw do
  resources :posts
  get 'pages/home'
  devise_for :users
  resources :users
  post 'users/new'
  resources :assisteds
  root to: 'pages#home'
  get 'welcome/index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/assisted.rb
class Assisted < ApplicationRecord
  has_many :posts, dependent: :destroy
  validates_presence_of :name, :gender, :address, :name_mother, :name_father, :cpf, :phone1, :email, presence: { message: 'Campo deve ser preenchido' }
  def posts
    posts = []
    posts = Post.where(assisted_id: self.id)
    return posts
  end

end

app/controllers/assisteds_controller.rb
class AssistedsController < ApplicationController
  before_action :set_assisted, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /assisteds
  # GET /assisteds.json
  def index
    if params[:commit] == 'Search'
      if params[:search] == "CPF"
        @assisteds = Assisted.where(cpf: params['input'])
      elsif params[:search] == 'Nome'
        @assisteds = Assisted.where("name LIKE ?", "%" + params['input'] + "%")
      elsif params[:search] == 'Email'
        @assisteds = Assisted.where(email: params['input'])
      elsif params[:search] == 'Status'
        if params['status_seach'] == 'inativo'
          @assisteds = Assisted.where(status: '0')
        else
          @assisteds = Assisted.where(status: '1')
        end
      end
      if @assisteds.blank?
        flash[:error] = "Nada foi encontrado."
      else

        flash[:notice] = "Busca realizada com sucesso."
      end
    end
  end

  # GET /assisteds/1
  # GET /assisteds/1.json
  def show
  end

  # GET /assisteds/new
  def new
    @assisted = Assisted.new
  end

  # GET /assisteds/1/edit
  def edit
  end

  # POST /assisteds
  # POST /assisteds.json
  def create
    @assisted = Assisted.new(assisted_params)

    respond_to do |format|
      if @assisted.save
        format.html { redirect_to @assisted, notice: 'Assisted was successfully created.' }
        format.json { render :show, status: :created, location: @assisted }
      else
        format.html { render :new }
        format.json { render json: @assisted.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assisteds/1
  # PATCH/PUT /assisteds/1.json
  def update
    respond_to do |format|
      if @assisted.update(assisted_params)
        format.html { redirect_to @assisted, notice: 'Assisted was successfully updated.' }
        format.json { render :show, status: :ok, location: @assisted }
      else
        format.html { render :edit }
        format.json { render json: @assisted.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assisteds/1
  # DELETE /assisteds/1.json
  def destroy
    @assisted.destroy
    respond_to do |format|
      format.html { redirect_to assisteds_url, notice: 'Assisted was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_assisted
      @assisted = Assisted.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def assisted_params
      params.require(:assisted).permit(:name, :gender, :address, :name_mother, :cpf, :status, :name_father, :phone1, :phone2, :email, :observation)
    end
end

app/helpers/assisteds_helper.rb
module AssistedsHelper
end

app/views/assisteds/_form.html.erb
<%= form_with(model: assisted, local: true) do |form| %>
  <% if assisted.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(assisted.errors.count, "error") %> prohibited this assisted from being saved:</h2>

      <ul>
      <% assisted.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


      <div class="main-panel">
        <!-- Navbar -->
            <div class="jumbotron jumbotron-sm">
        <div class="container">
            <div class="row">
                <div class="col-sm-12 col-lg-12">
                    <h1 class="h1">
                        Perfil do Usuário</h1>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <div class="well well-sm">
                    <form>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                              <%= form.text_field :name, class: 'form-control', placeholder: 'Nome' %>
                            </div>
                            <div class="form-group">
                              <%= form.select :gender, [['_______M_______', true], ['_______F_______', false]], prompt: 'Selecione o Sexo' %>
                            </div>
                            <div class="form-group">
                              <%= form.text_field :address, class: 'form-control', placeholder: 'Endereço' %>
                            </div>
                            <div class="form-group">
                              <%= form.text_field :name_mother, class: 'form-control', placeholder: 'Nome da mãe' %>
                            </div>
                            <div class="form-group">
                              <%= form.text_field :name_father, class: 'form-control', placeholder: 'Nome do pai' %>
                            </div>
                            <div class="form-group">
                              <%= form.text_field :cpf, class: 'form-control', placeholder: 'CPF' %>
                            </div>
                            <div class="form-group">
                              <%= form.select :status, [['ativo', true], ['inativo', false]], prompt: 'Selecione o status' %>
                            </div>
                            <div class="form-group">
                              <%= form.number_field :phone1, class: 'form-control', placeholder: 'Telefone 1' %>
                            </div>
                            <div class="form-group">
                              <%= form.number_field :phone2, class: 'form-control', placeholder: 'Telefone 2' %>
                            </div>
                            <div class="form-group">
                              <%= form.text_field :email, class: 'form-control', placeholder: 'Email' %>
                            </div>
                            <div class="form-group">
                              <%= form.text_area :observation, class: 'form-control', placeholder: 'Observação' %>
                            </div>
                            <%= form.submit 'Confirmar', class: 'btn btn-primary' %>
                        </div>
                    </div>
                    </form>
                </div>
            </div>

        </div>
    </div>



<% end %>

app/views/assisteds/edit.html.erb
<%= render 'form', assisted: @assisted %>

app/views/assisteds/index.html.erb
<% if params[:commit] %>
  <% if @assisteds.present? %>
    <div class="alert alert-primary" role="alert">
      This is a primary alert with <a href="#" class="alert-link">an example link</a>. Busca realizada com sucesso.
    </div>
  <% else %>
    <div class="alert alert-primary" role="alert">
      This is a primary alert with <a href="#" class="alert-link">an example link</a>. Nada foi encontrado.
    </div>
  <% end %>
<% end %>



  <div class="main-panel">
    <div class="jumbotron jumbotron-sm">
      <div class="container">
        <div class="row">
          <div class="col-sm-12 col-lg-12">
            <h3 class="h1"><b>Busca por usuários</b></h3>
          </div>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="right_bar ">
        <div class="tab-content ">
      		<div class="tab-pane fade show active" id="lorem" role="tabpanel">
            <%= form_tag("/assisteds", method: "get") do %>
                <div class="form-group">
                  <%= label_tag(:q, "Procurar por:") %>
                  <div class="col-md-8">
                    <%= select_tag "search", options_for_select([ "CPF", "Nome", "Email", "Status" ], params['search']), class: "custom-select" %>
                  </div>
                </div>
                <div class="form-group" id="input_search">
                  <%= label_tag(:q, "") %>
                  <div class="col-md-8">
                    <%= text_field_tag :input, value = "#{params['input']}", class: 'form-control', style: 'width:50%;', placeholder: 'Insira o valor' %>
                  </div>
                </div>
                <div class="form-group" id="status_seach_input">
                  <%= label_tag(:q, "Status:") %>
                  <div class="col-md-8">
                    <%= select_tag "status_seach", options_for_select([ "ativo", "inativo" ], params['status_seach']), class: "custom-select" %>
                  </div>
                </div>
                <%= submit_tag("Search") %>

              </div>
            <% end %>

            <% if @assisteds.present? %>

              <table class="table table-hover table-sm table-properties">
                <thead>
                  <tr>
                    <th>Name</th>
                    <th>Gender</th>
                    <th>Phone1</th>
                    <th>Email</th>
                    <th>CPF</th>
                    <th>Status</th>
                    <th colspan="6"></th>
                  </tr>
                </thead>
                <tbody>
                <% @assisteds.each do |assisted| %>
                  <tr>
                    <td><%= assisted.name %></td>
                    <td><%= assisted.gender? ? "Masculino" : "Feminino" %></td>
                    <td><%= assisted.phone1 %></td>
                    <td><%= assisted.email %></td>
                    <td><%= assisted.cpf %></td>
                    <td><%= assisted.status? ? "Ativo" : "Inativo" %></td>
                    <td><%= link_to 'Show', assisted %></td>
                    <td><%= link_to 'Edit', edit_assisted_path(assisted) %></td>
                    <td><% link_to 'Destroy', assisted, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                  </tr>
                <% end %>
                </tbody>
              </table>
            <% end %>
          </div>
        </div>
      </div>
    </div>


<script>
$(document).ready(function(){
  var search = document.getElementById("search");
  var status_seach = document.getElementById("status_seach_input");
  var input = document.getElementById("input_search");
  $('#search').change(function(e) {
    read();
  });

  function read() {
    if (search.value == "Status") {
        status_seach.style.display = "block";
        input.style.display = "none";
    } else {
        status_seach.style.display = "none";
        input.style.display = "block";
    }
  }
  read();
});
  </script>

</body>

<br>

app/views/assisteds/new.html.erb
<%= render 'form', assisted: @assisted %>

app/views/assisteds/show.html.erb
<p id="notice"><%= notice %></p>

    <div class="main-panel">
      <div class="jumbotron jumbotron-sm">
        <div class="container">
          <div class="row">
            <div class="col-sm-12 col-lg-12">
              <h1 class="h1"><b><%= @assisted.name %></b></h1>
            </div>
          </div>
        </div>
      </div>
      <div class="container">


        <h3>Dados Pessoais   <%= link_to 'Editar', edit_assisted_path(@assisted), class: 'btn btn-primary btn-sm' %></h3>


        <table class="table table-hover table-sm table-properties">
            <tr style="color:#ff4d4d">
              <th>Observação</th>
              <td><p><%= @assisted.observation %></p></td>
            </tr>
            <tr>
              <th>Sexo</th>
              <td>
                <% if @assisted.gender %>
                  Masculino
                <% else %>
                  Feminino
                <% end %>
              </td>
            </tr>
            <tr>
              <th>Endereço</th>
              <td><%= @assisted.address %></td>
            </tr>
            <tr>
              <th>Nome da mãe</th>
              <td><%= @assisted.name_mother %></td>
            </tr>
            <tr>
              <th>Nome do pai</th>
              <td><%= @assisted.name_father %></td>
            </tr>
            <tr>
              <th>Telefone 1</th>
              <td><%= @assisted.phone1 %></td>
            </tr>
            <tr>
              <th>Telefone 2</th>
              <td><%= @assisted.phone2 %></td>
            </tr>
            <tr>
              <th>Email</th>
              <td><%= @assisted.email %></td>
            </tr>
          </table>

          <%= link_to new_post_path(assisted_id: @assisted.id) do %>
            <button type="button" class="btn btn-primary btn-block">Novo Registro</button>
          <% end %>
          <br>
          <h2>Registros</h2>
          <% if @assisted.posts.any? %>
          <%= @assisted.posts.each do |post| %>
            <div class="container-fluid p-3 my-3 border">
              <h2><%= post.title %></h2>
              <footer>
                Criado por <%= post.user.username %> - ID <%= post.user.id %> em <%= post.formatted_date %>
              </footer>
              <br>
              <pre>
                <%= simple_format(post.body) %>
              </pre>
            </div>
          <% end %>
        <% else %>
          <p>Sem registros</p>
        <% end %>



      </div>




    </div>




  </div>




















































































</body>