config/routes.rb
Rails.application.routes.draw do
  resources :posts
  get 'pages/home'
  devise_for :users
  resources :users
  post 'users/new'
  resources :assisteds
  root to: 'pages#home'
  get 'welcome/index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_side_menu.html.erb
<body class="" style="margin:0px">
  <div class="wrapper ">
    <div class="sidebar" data-color="purple" data-background-color="purple">
      <div class="logo">
        <%= link_to 'Minds', pages_home_path, class: 'simple-text logo-normal' %>
      </div>
      <div class="sidebar-wrapper">
        <ul class="nav">
          <li class="nav-item ">
            <%= link_to assisteds_path, class: 'nav-link' do %>
              <i class="material-icons">person</i>
              <p>Buscar usuário</p>
            <% end %>
            </a>
          </li>
          <li class="nav-item ">
            <%= link_to new_assisted_path, class: 'nav-link' do %>
              <i class="material-icons">person_add</i>
              <p>Cadastrar novo usuário</p>
            <% end %>
            </a>
          </li>
          <li class="nav-item ">
            <%= link_to posts_path, class: 'nav-link' do %>
              <i class="material-icons">library_books</i>
              <p>Lista de Registros</p>
            <% end %>
            </a>
          </li>
          <% if current_user.admin %>
            <li class="nav-item ">
              <%= link_to users_path, class: 'nav-link' do %>
                <i class="material-icons">library_books</i>
                <p>Lista de Assistentes</p>
              <% end %>
              </a>
            </li>
            <li class="nav-item ">
              <%= link_to new_user_path, class: 'nav-link' do %>
                <i class="material-icons">library_books</i>
                <p>Cadastrar assistente</p>
              <% end %>
              </a>
            </li>
          <% end %>
          <li class="nav-item ">
            <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link' do %>
              <i class="material-icons"></i>
              <p>Sair</p>
            <% end %>
            </a>
          </li>
        </ul>
      </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjetoMinds</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- <%= render 'layouts/alerts' %> -->
    <% if current_user %>
    <%= render 'layouts/side_menu' %>
    <% end %>
    <%= yield %>
  </body>
</html>